# Generated by Django 5.1.7 on 2025-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
