# Generated by Django 5.1.7 on 2025-05-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Communication', 'Communication'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(blank=True, choices=[('15days', '15 Days'), ('1m', '1 Month'), ('2m', '2 Months'), ('3m', '3 Months'), ('6m', '6 Months')], max_length=20),
        ),
    ]
