# Generated by Django 5.1.7 on 2025-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_task_category_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='badge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
