# Generated by Django 5.1.7 on 2025-05-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_badge_task_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
    ]
