# Generated by Django 5.1.7 on 2025-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_task_badge_remove_task_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.CharField(blank=True, choices=[('15days', '15 Days'), ('1 Month', '1 Month'), ('2 Month', '2 Months'), ('3 Month', '3 Months'), ('6 Month', '6 Months')], max_length=20),
        ),
    ]
